default:
  image: python:3-slim

stages:
  - test
  - build
  - publish
  - deploy

test:
  stage: test
  image: apache/airflow:2.1.2
  entrypoint: ["bash"]
  before_script:
    - airflow db init
  script: 
   - airflow dags list 

